### ISSUE TITLE
Module not downloaded yet

### ISSUE THREAD

**Issue by kewp** [lucacasonato/fresh-with-signals#5]
Trying to run this and getting the following error:

```
An error occurred during route handling or page rendering. Error: Build failed with 1 error:
error: Module not downloaded yet.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11
    at eventLoopTick (ext:core/01_core.js:183:11) {
  errors: [
    {
      detail: Error: Module not downloaded yet.
    at loadFromCLI (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:56:28)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async load (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:18:14)
    at async callback (https://deno.land/x/esbuild@v0.14.51/mod.js:970:28)
    at async handleRequest (https://deno.land/x/esbuild@v0.14.51/mod.js:698:30),
      id: "",
      location: null,
      notes: [],
      pluginName: "deno",
      text: "Module not downloaded yet."
    }
  ],
  warnings: []
}
```

```
> deno --version
deno 1.36.4 (release, aarch64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6
```

I saw someone mentioned in Discord it's because Deno is not compatible with Fresh? But that message was in April.

**Comment by hashrock** [comment]
In [my other project](https://github.com/hashrock/tabler-icons-tsx) where I used `fresh 1.1.2`, I encountered the same error with `deno 1.37.1`.

However, after updating fresh to `fresh@1.4.3`, the error disappeared.

Could it be a compatibility issue with the older version of fresh? what if applying fresh auto updater

**Comment by kewp** [comment]
hey @hashrock thanks, this did fix it for me.

just to be clear (for other beginners) i had to:

- change `import_map.json` line to `"$fresh/": "https://deno.land/x/fresh@1.4.3/",`
- run `deno run --reload -A main.ts`
